# Generated by Django 5.0.7 on 2024-08-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tag",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
